export const CHANGE_MAIN_SLIDE = 'HOME/CHANGE_MAIN_SLIDE';
export const REQUEST_HOME = 'HOME/REQUEST_HOME';
export const STOP_MAIN_SLIDER_ANIMATION = 'HOME/STOP_MAIN_SLIDER_ANIMATION';
export const SET_MAIN_SLIDE = 'HOME/SET_MAIN_SLIDER';
