export const CHANGE_MAIN_SLIDE = 'HOME/CHANGE_MAIN_SLIDE';
export const REQUEST_HOME = 'HOME/REQUEST_HOME';
export const DISANIMATE_MAIN_SLIDER = 'HOME/DISANIMATE_MAIN_SLIDE';
export const SET_MAIN_SLIDE = 'HOME/SET_MAIN_SLIDER';
